# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6db0761ff155b70cd1095788e1c9a3d1b12d41974152ab4a506b1b7188337a21e89932f5cd47b622aa6eda58f460acf2c49f95ffc114663bb506a6272e3bb39e

test:
  secret_key_base: 03bbb39d63f0e2e821da70aa6296634d2689c7f290f30273b26222c844531607f15629be15944bab48775bed6848b1e44c5d9c7171f73c4aadde401af2e652c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
